### ISSUE TITLE
Ansible install_jenkins.yaml FAILS to create master - missing dependency of "daemonize"

### ISSUE THREAD

**Issue by Glocktober** [linuxacademy/content-deploying-to-aws-ansible-terraform#6]
Maybe with some version or other of Jenkins a new dependency was added from "daemonize" - here is the output I get running this lab:  specifically install_jenkins.yaml playbook fails:

 TASK [install Jenkins] *********************************************************
 fatal: [54.145.170.3]: FAILED! => {"changed": false, "changes": {"installed": ["jenkins"]}, "msg": "Error: Package: jenkins- 
 2.316-1.1.noarch (jenkins)\n           Requires: daemonize\n", "rc": 1, "results": ["Loaded plugins: extras_suggestions, 
 langpacks, priorities, update-motd\nResolving Dependencies\n--> Running transaction check\n---> Package 
 jenkins.noarch 0:2.316-1.1 will be installed\n--> Processing Dependency: daemonize for package: jenkins-2.316 -1.1.noarch\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You 
 could try running: rpm -Va --nofiles --nodigest\n"]}

It turns out daemonize is part of the epel release, so that has to be added as well.

to get this to work I edited install_jenkins.yaml to add a task before the "install dependencies" to install the epel release, and then added daemonize to the dependencies:
...
```yaml
# install_jenkins.yaml modified
---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: install epel
      shell: /usr/bin/amazon-linux-extras install epel -y
 
    - name: install dependencies
      yum:
        name: "{{ package }} "
        state: present
      vars:
        package:
        - wget
        - java-1.8.0-openjdk-devel
        - git
        - daemonize
... rest of file...

```
This worked for me.
